language: php

php:
  - 5.5

before_script:
  - mysql -e 'create database travis;'
  - composer install --no-interaction --dev --prefer-dist
  - php -S 127.0.0.1:8000 server.php &
  - ./artisan migrate

script:
  - vendor/bin/codecept run --steps
  - kill %1